# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_track_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='date_created',
        ),
    ]
