# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_track_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_title',
            field=models.CharField(default='Untitled', max_length=300),
        ),
    ]
