# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50)),
                ('event_title', models.CharField(max_length=50)),
                ('event_info', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=75)),
            ],
        ),
    ]
