# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_location', models.CharField(max_length=100)),
                ('artist_bio', models.CharField(max_length=1000)),
                ('artist_picture', models.CharField(max_length=1500)),
                ('example_tracks', models.CharField(max_length=1000)),
            ],
        ),
    ]
