# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=1000)),
                ('picture', models.CharField(max_length=1500)),
                ('tracks', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Bio',
        ),
    ]
